package assets_services

import (
	"bytes"
	"context"
	"errors"
	"image"
	"strings"
	"testing"

	"github.com/kastoras/images-api/internal/imageprocessing"
	"github.com/kastoras/images-api/internal/server"
)

func TestRender_GeneratesAndCachesDerivative(t *testing.T) {
	st := newFakeStorage()
	svc := newTestService(st)
	m := createMaster(t, svc, "acme", "t1")
	opts := imageprocessing.ResizeOptions{Width: 50, Height: 50, Mode: imageprocessing.ResizeModeExact}

	data, ct, err := svc.Render(context.Background(), "acme", "t1", m.ID, opts, "")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if ct != "image/jpeg" {
		t.Errorf("content type = %s", ct)
	}
	if w, h := decodeDims(t, data); w != 50 || h != 50 {
		t.Errorf("derivative is %dx%d", w, h)
	}
	if !st.has(derivativeKey("acme", "t1", m.ID, 50, 50, "exact", "jpg")) {
		t.Errorf("derivative not cached; keys=%v", st.keys())
	}

	// Second request must be served from cache: no new upload, master not re-read.
	uploads, downloads := st.uploads, st.downloads
	cached, _, err := svc.Render(context.Background(), "acme", "t1", m.ID, opts, "")
	if err != nil {
		t.Fatalf("cached Render: %v", err)
	}
	if !bytes.Equal(cached, data) {
		t.Error("cached bytes differ from generated bytes")
	}
	if st.uploads != uploads {
		t.Error("cache hit must not upload")
	}
	if st.downloads != downloads+1 {
		t.Errorf("cache hit should download exactly the derivative, downloads went %d -> %d", downloads, st.downloads)
	}
}

func TestRender_FormatOverride(t *testing.T) {
	st := newFakeStorage()
	svc := newTestService(st)
	m := createMaster(t, svc, "acme", "t1")
	opts := imageprocessing.ResizeOptions{Width: 40, Height: 40, Mode: imageprocessing.ResizeModeExact}

	data, ct, err := svc.Render(context.Background(), "acme", "t1", m.ID, opts, "png")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if ct != "image/png" {
		t.Errorf("content type = %s", ct)
	}
	if _, format, err := image.DecodeConfig(bytes.NewReader(data)); err != nil || format != "png" {
		t.Errorf("expected png payload, got %q err=%v", format, err)
	}
	if !st.has(derivativeKey("acme", "t1", m.ID, 40, 40, "exact", "png")) {
		t.Errorf("png derivative not cached; keys=%v", st.keys())
	}
}

func TestRender_NotFound(t *testing.T) {
	svc := newTestService(newFakeStorage())
	_, _, err := svc.Render(context.Background(), "acme", "t1", strings.Repeat("a", 64), imageprocessing.ResizeOptions{Width: 10, Height: 10, Mode: imageprocessing.ResizeModeExact}, "")
	if !errors.Is(err, server.ErrNotFound) {
		t.Errorf("expected ErrNotFound, got %v", err)
	}
}

func TestRender_TenantIsolation(t *testing.T) {
	svc := newTestService(newFakeStorage())
	m := createMaster(t, svc, "acme", "t1")
	opts := imageprocessing.ResizeOptions{Width: 10, Height: 10, Mode: imageprocessing.ResizeModeExact}

	for _, c := range [][2]string{{"acme", "t2"}, {"other", "t1"}} {
		if _, _, err := svc.Render(context.Background(), c[0], c[1], m.ID, opts, ""); !errors.Is(err, server.ErrNotFound) {
			t.Errorf("%v should not see acme/t1's master, got %v", c, err)
		}
	}
}

func TestRender_MasterDownloadFailure(t *testing.T) {
	st := newFakeStorage()
	svc := newTestService(st)
	m := createMaster(t, svc, "acme", "t1")
	boom := errors.New("boom")
	st.downloadErr[masterKey("acme", "t1", m.ID, extForFormat(m.Format))] = boom

	_, _, err := svc.Render(context.Background(), "acme", "t1", m.ID, imageprocessing.ResizeOptions{Width: 10, Height: 10, Mode: imageprocessing.ResizeModeExact}, "")
	if !errors.Is(err, boom) {
		t.Errorf("expected wrapped boom, got %v", err)
	}
}

func TestRender_CorruptMaster(t *testing.T) {
	st := newFakeStorage()
	svc := newTestService(st)
	hash := strings.Repeat("b", 64)
	st.put(masterKey("acme", "t1", hash, "jpg"), []byte("garbage"))

	_, _, err := svc.Render(context.Background(), "acme", "t1", hash, imageprocessing.ResizeOptions{Width: 10, Height: 10, Mode: imageprocessing.ResizeModeExact}, "")
	if err == nil || !strings.Contains(err.Error(), "decode master") {
		t.Errorf("expected decode master error, got %v", err)
	}
}

func TestRender_UploadFailure(t *testing.T) {
	st := newFakeStorage()
	svc := newTestService(st)
	m := createMaster(t, svc, "acme", "t1")
	boom := errors.New("boom")
	st.uploadErr = boom

	_, _, err := svc.Render(context.Background(), "acme", "t1", m.ID, imageprocessing.ResizeOptions{Width: 10, Height: 10, Mode: imageprocessing.ResizeModeExact}, "")
	if !errors.Is(err, boom) {
		t.Errorf("expected wrapped boom, got %v", err)
	}
}
